### ISSUE TITLE
Viewing the RCV transfers doesn't work if a candidates has been manually eliminated

### ISSUE THREAD

**Issue by khuey** [dbaron/sf-elections-rcv#8]
STR:

1. Load the Nov 5, 2019 election, Preliminary Report 4, and select the DA's race.
2. Manually eliminate Nancy Tung by unselecting her in the Candidate Filter box.
3. Click on the final result for one of the candidates to see where their votes come from.

Observe:
- The transfers box is not filled in with data
- `TypeError: Object.values(...).find(...) is undefined sf-elections-rcv:1200:60` is visible in the JS console

**Comment by khuey** [comment]
And to elaborate a bit, the point of this was to be able to restrict the ballots considered to certain sub-populations (e.g. VBM, D5 only) and then force the last two candidates to be Loftus and Boudin so I could examine what contributions were made to the actual results from those sub-populations.

**Comment by dbaron** [comment]
And, for what it's worth, this was a regression from f2dd6ab05b3b387729a77a3c2177d6a436a042a5 where I rewrote this to handle an arbitrary number of ranks rather than just three.
